Update and rename test to test2

diff --git a/test2 b/test2
--- a/test2
+++ b/test2
@@ -22,20 +22,20 @@ fi
 # CREATE AUTOBOT DIRECTORY  
 #-----------------------------------------------------------------------------------------------------
 
-create_dir="/root/remblock/autobot"
+create_dir="/root/remblock/autobot2"
 
 #-----------------------------------------------------------------------------------------------------
 # CREATE AUTOBOT CONFIG FILE
 #-----------------------------------------------------------------------------------------------------
 
-config_file="/root/remblock/autobot/config"
+config_file="/root/remblock/autobot2/config"
 
 #-----------------------------------------------------------------------------------------------------
 # BP MONITOR SCRIPT AND CONFIG PATHS
 #-----------------------------------------------------------------------------------------------------
 
 bp_monitor_script_path="/root/remblock/autobot/bpmonitor.sh"
-bp_monitor_config_path="$config_file"
+bp_monitor_config_path="/root/remblock/autobot/config"
 
 #-----------------------------------------------------------------------------------------------------
 # MINUTES TO WAIT BETWEEN EACH EXECUTIONS OF THE SCRIPT
@@ -224,19 +224,24 @@ fi
 function create_bp_monitor_files(){
 cat << 'DOC' > $bp_monitor_script_path
 #!/bin/bash
+
 #This script need to be called via cron every minute
+
 #PATH to used commands
 PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
+
 #Load configuration variables and values
 source "/root/remblock/autobot/config" &>/dev/null
 now_epoch="$(date +%s)"
 now_date="$(date +%d-%m-%Y)"
 owneraccountname="$owner"
+
 #Install crontab line if it does not exists
 if [ ! -z "$bpm_cron_cmd" ] && ! crontab -u root -l | grep -v '^ *#' | grep "$bpm_cron_cmd" &>/dev/null
 then
   (crontab -u root -l ; echo "*/1 * * * * $bpm_cron_cmd") | crontab -u root -
 fi
+
 #Create bpmonitor folder for temporal information
 if [ ! -z "$bpm_temp_dir" ] && [ ! -d "$bpm_temp_dir" ]
 then
@@ -248,7 +253,6 @@ fi
 #****************************************************************************************************#
 
 #Add a message to be sent later, if there are more lines than permited in the queue, delete the older ones
-
 function add_message_to_queue(){
   #If the log is at maximum capacity, delete exceding lines
   if [ -f "$bpm_temp_dir/msg_queue.txt" ] && (( $(wc -l "$bpm_temp_dir/msg_queue.txt" | awk '{print $1}') >= bpm_max_queued_msg_lines ))
@@ -437,30 +441,37 @@ if [ "$(echo $bpm_check_producer | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_produce_minutes
 fi
+
 if [ "$(echo $bpm_check_log | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_log_minutes
 fi
+
 if [ "$(echo $bpm_check_info | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_remnode_chain
 fi
+
 if [ "$(echo $bpm_check_blocks | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_block_minutes
 fi
+
 if [ "$(echo $bpm_check_irr_blocks | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_last_iblock
 fi
+
 if [ "$(echo $bpm_check_peers | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_net_peers
 fi
+
 if [ "$(echo $bpm_check_server | tr '[:upper:]' '[:lower:]' )" == "true" ]
 then 
   check_disk_and_ram
 fi
+
 send_warnings
 DOC
 
@@ -704,163 +715,132 @@ then
 # GET AUTOMATED RESTAKING ANSWER FROM THE USER OR TAKE IT FROM THE CONFIG FILE
 #-----------------------------------------------------------------------------------------------------
 
-if get_config_value auto_restaking
-then
-  if [ "$global_value" = "true" ]
+  if get_config_value auto_restaking
   then
-    auto_restaking=true
-  fi
-else
-  if $at
-  then
-    exit 2
-  fi
-  if get_user_answer_yn "DO YOU WANT AUTOBOT TO AUTO RESTAKE YOUR REWARDS"
-  then
-    auto_restaking=true
-    echo "auto_restaking=true" >> "$config_file"
+    if [ "$global_value" = "true" ]
+    then
+      auto_restaking=true
+    fi
   else
-    echo "auto_restaking=false" >> "$config_file"
+    if $at
+    then
+      exit 2
+    fi
+    if get_user_answer_yn "DO YOU WANT AUTOBOT TO AUTO RESTAKE YOUR REWARDS"
+    then
+      auto_restaking=true
+      echo "auto_restaking=true" >> "$config_file"
+    else
+      echo "auto_restaking=false" >> "$config_file"
+    fi
+    echo 
   fi
-  echo 
-fi
 
 #-----------------------------------------------------------------------------------------------------
 # GET THE RESTAKING PERCENTAGE FROM THE USER OR TAKE IT FROM THE CONFIG FILE
 #-----------------------------------------------------------------------------------------------------
 
-if $auto_restaking
-then
-  if get_config_value restakingpercentage
+  if $auto_restaking
   then
-    restakingpercentage="$global_value"
-  else
-    if $at
+    if get_config_value restakingpercentage
     then
-      exit 2
+      restakingpercentage="$global_value"
+    else
+      if $at
+      then
+        exit 2
+      fi
+      read -p "PLEASE SET YOUR RESTAKING PERCENTAGE: " -e restakingpercentage
+      echo "restakingpercentage=$restakingpercentage" >> "$config_file"
+      echo 
     fi
-    read -p "PLEASE SET YOUR RESTAKING PERCENTAGE: " -e restakingpercentage
-    echo "restakingpercentage=$restakingpercentage" >> "$config_file"
-    echo 
-  fi
-  restakingpercentage=$(echo $restakingpercentage | tr -d '%' )
+    restakingpercentage=$(echo $restakingpercentage | tr -d '%' )
     
 #-----------------------------------------------------------------------------------------------------
 # GET RESTAKING NOTIFCATION ANSWER FROM THE USER OR TAKE IT FROM THE CONFIG FILE
 #-----------------------------------------------------------------------------------------------------
 
- if get_config_value auto_restaking_alert
- then
-   if [ "$global_value" = "true" ]
-   then
-     auto_restaking_alert=true
-   fi
-  else
-    if $at
+    if get_config_value auto_restaking_alert
     then
-      exit 2
-    fi
-    if get_user_answer_yn "DO YOU WANT TO RECEIVE RESTAKING NOTIFICATIONS"
-    then
-      auto_restaking_alert=true
-      echo "auto_restaking_alert=true" >> "$config_file"
+      if [ "$global_value" = "true" ]
+      then
+        auto_restaking_alert=true
+      fi
     else
-      echo "auto_restaking_alert=false" >> "$config_file"
+      if $at
+      then
+        exit 2
+      fi
+      if get_user_answer_yn "DO YOU WANT TO RECEIVE RESTAKING NOTIFICATIONS"
+      then
+        auto_restaking_alert=true
+        echo "auto_restaking_alert=true" >> "$config_file"
+      else
+        echo "auto_restaking_alert=false" >> "$config_file"
+      fi
+      echo 
     fi
-    echo 
   fi
-fi
   
 #-----------------------------------------------------------------------------------------------------
-# GET AUTOMATED TRANSFER ANSWER FROM THE USER OR TAKE IT FROM THE CONFIG FILE
+# ASK THE USER FOR THE TRANSFER ACCOUNT NAME, TRANSFER PERCENTAGE AND TRANSFER NOTIFICATIONS
 #-----------------------------------------------------------------------------------------------------
 
-if get_config_value auto_transfer
-then
-  if [ "$global_value" = "true" ]
-  then
-    auto_transfer=true
-  fi
-else
-  if $at
-  then
-    exit 2
-  fi
-  if get_user_answer_yn "DO YOU WANT AUTOBOT TO AUTO TRANSFER YOUR REWARDS"
-  then
-    auto_transfer=true
-    echo "auto_transfer=true" >> "$config_file"
-  else
-    echo "auto_transfer=false" >> "$config_file"
-  fi
-  echo 
-fi
-  
-#-----------------------------------------------------------------------------------------------------
-# GET TRANSFER ACCOUNT NAME FROM THE USER OR TAKE IT FROM THE CONFIG FILE
-#-----------------------------------------------------------------------------------------------------
-  
-if get_config_value auto_transfer
-then
-  if [ "$global_value" = "true" ]
-  then
-    auto_transfer_acct="$global_value"
-  fi
-else
-  if $at
-  then
-    exit 2
-  fi
-  read -p "PLEASE SET YOUR TRANSFER ACCOUNT NAME: " -e auto_transfer_acct
-  auto_transfer=true
-  echo "auto_transfer_acct=$auto_transfer_acct" >> "$config_file"
-  echo 
-  fi 
-fi
-  
-#-----------------------------------------------------------------------------------------------------
-# GET THE TRANSFER PERCENTAGE FROM THE USER OR TAKE IT FROM THE CONFIG FILE
-#-----------------------------------------------------------------------------------------------------
-  
-if $auto_transfer
-then
-  if get_config_value auto_transfer_perc
-  then
-    auto_transfer_perc="$global_value"
-  else
-    if $at
-    then
-      exit 2
-    fi
-    read -p "PLEASE SET YOUR TRANSFER PERCENTAGE: " -e auto_transfer_perc
-    echo "auto_transfer_perc=$auto_transfer_perc" >> "$config_file"
-    echo 
-  fi
-  auto_transfer_perc=$(echo $auto_transfer_perc | tr -d '%' )
-    
-#-----------------------------------------------------------------------------------------------------
-# GET TRANSFER NOTIFCATION ANSWER FROM THE USER OR TAKE IT FROM THE CONFIG FILE
-#-----------------------------------------------------------------------------------------------------
-
-  if get_config_value auto_transfer_alert
+  if get_config_value auto_transfer
   then
     if [ "$global_value" = "true" ]
     then
-      auto_transfer_alert=true
+      auto_transfer=true
+      if get_config_value auto_transfer_acct
+      then
+        auto_transfer_acct="$global_value"
+      else
+        echo "ERROR: auto_transfer_acct must be set when using auto_transfer"
+	exit 1
+      fi
+      if get_config_value auto_transfer_perc
+      then
+        auto_transfer_perc="$global_value"
+      else
+        echo "ERROR: auto_transfer_perc must be set when using auto_transfer"
+	exit 1
+      fi
+      if get_config_value auto_transfer_alert
+      then
+        auto_transfer_alert="$global_value"
+      else
+        echo "ERROR: auto_transfer_alert must be set when using auto_transfer"
+	exit 1
+      fi
     fi
   else
     if $at
     then
       exit 2
     fi
-    if get_user_answer_yn "DO YOU WANT TO RECEIVE TRANSFER NOTIFICATIONS"
+    if get_user_answer_yn "DO YOU WANT AUTOBOT TO AUTO TRANSFER YOUR REWARDS"
     then
-      auto_transfer_alert=true
-      echo "auto_transfer_alert=true" >> "$config_file"
+      auto_transfer=true
+      echo "auto_transfer=true" >> "$config_file"
+      echo
+      read -p "PLEASE SET YOUR TRANSFER ACCOUNT NAME: " -e auto_transfer_acct
+      echo "auto_transfer_acct=$auto_transfer_acct" >> "$config_file"
+      echo
+      read -p "PLEASE SET YOUR TRANSFER PERCENTAGE: " -e auto_transfer_perc
+      auto_transfer_perc=$(echo $auto_transfer_perc | tr -d '%' )
+      echo "auto_transfer_perc=$auto_transfer_perc" >> "$config_file"
+      echo
+      if get_user_answer_yn "DO YOU WANT TO RECEIVE TRANSFER NOTIFICATIONS"
+      then
+        auto_transfer_alert=true
+        echo "auto_transfer_alert=true" >> "$config_file"
+      else
+        echo "auto_transfer_alert=false" >> "$config_file"
+      fi 
     else
-      echo "auto_transfer_alert=false" >> "$config_file"
-    fi
-    echo 
+      echo "auto_transfer=false" >> "$config_file"
+    fi 
+    echo
   fi
 fi
 
@@ -979,12 +959,7 @@ fi
 
 if $auto_transfer
 then
-  if (( auto_transfer_perc == 100 ))
-  then
-    transfer_amount="$total_reward"
-  else
-    transfer_amount="$(echo "scale=4; ( $total_reward / 100 ) * $auto_transfer_perc" | bc )"
-  fi
+  transfer_amount="$(echo "scale=4; ( $total_reward / 100 ) * $auto_transfer_perc" | bc )"
   output=$(remcli transfer $owneraccountname $auto_transfer_acct "$transfer_amount REM" -x 120 -p $owneraccountname@$transfer_permission -f 2>&1)
   #Uncomment if you want the output of the command printed
   #if ! $at; then echo $output; fi
